chore: refresh PSS policies with latest changes
nirmata-add-ons/policies pull request #11
Opened 2022-10-19 11:28 UTC by pankajatnirmata

Signed-off-by: Pankaj Khushalani <pankaj.khushalani@nirmata.com>

Referring to the changes made in [PR#420](https://github.com/kyverno/policies/pull/420) and [PR#421](https://github.com/kyverno/policies/pull/421) of `kyverno/policies`, the PSS policy `pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict.yaml` required the following updates -

- Sending `drop[]` and `add[]` policies to `to_upper()` to be case insensitive
- Allowing policy to go in BACKGROUND mode if `request.operation` cannot be resolved

2022-10-19 11:59 UTC, chipzoller requested changes
Syntax errors.

2022-10-19 11:59 UTC, chipzoller commented on pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict.yaml
> +                  value: "{{ element.securityContext.capabilities.drop[].to_upper(@) || '[]' }}"
Check [here](https://kyverno.io/policies/pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict/). Should be backticks wrapping the brackets.

2022-10-19 11:59 UTC, chipzoller commented on pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict.yaml
> +                - key: "{{ element.securityContext.capabilities.add[].to_upper(@) || '[]' }}"
Same comment as above.

2022-10-19 13:00 UTC, chipzoller approved these changes

2022-10-19 18:31 UTC, atulatnirmata approved these changes
Looks good. I think it would be good to apply this to v3.5 branch as well.

2023-01-01 15:04 UTC, chipzoller commented
Need to walk this change back based on community updates.

https://github.com/kyverno/policies/pull/485/commits/b655dfb508edbc96c446f08cec87ec3cf0dff18f

2023-01-02 05:15 UTC, atulatnirmata commented
@chipzoller 
This change hasn't been merged yet.
From what I understand from https://github.com/kyverno/policies/commit/b655dfb508edbc96c446f08cec87ec3cf0dff18f, `to_upper` has to be removed from this patch, right?
And `BACKGROUND` change is still required, right?

2023-01-02 13:16 UTC, chipzoller commented
Change is merged. Yes, just remove to_upper.

2023-01-05 11:52 UTC, atulatnirmata commented
@chipzoller 
I meant this PR https://github.com/nirmata-add-ons/policies/pull/11 is not merged yet. I have created a new PR https://github.com/nirmata-add-ons/policies/pull/13 to address the change. Closing this PR.
For some reason, I am unable to add you as reviewer to that PR.

2023-01-05 11:52 UTC, closed without merging